spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  redis:
    host: localhost
    port: 6379
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false #osiv
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: true
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy:
        ant_path_matcher

naver:
  clientId: ${NAVER_CLIENT_ID}
  clientSecret: ${NAVER_CLIENT_SECRET}